#!/bin/sh -eu
export CLASSPATH=.:$(pwd)/data/javatools.jar
# Setup sandbox

check() {
  if ! type $1 > /dev/null ; then
    >&2 echo "ERROR: missing program $1"
    exit 1
  fi
}

check "flex"
check "bison"
check "hlint"
check "javac"
check "ocamllex"
check "ocamlyacc"

cabal sandbox init
cabal install --only-dependencies
