#!/bin/sh -eu

# Setup sandbox
cabal sandbox init
cabal install --only-dependencies
cabal sandbox add-source ../source
cabal install bnfc

check() {
  if ! type $1 > /dev/null ; then
    >&2 echo "ERROR: missing program $1"
    exit 1
  fi
}

check flex
check bison
check hlint
check javac
check jflex
check ocamllex
check ocamlyacc
