module Skel#110-backslash where

-- Haskell module generated by the BNF converter

import Abs#110-backslash
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transS :: S -> Result
transS x = case x of
  S  -> failure x



