# Makefile for BNFC tutorial
# Generates HTML from TXT

all:
	txt2tags -thtml bnfc-tutorial.txt
# Andreas, 2017-11-16, what is "htmls"?
# Cannot find it on my system nor the web.
# Commenting out...
#	htmls bnfc-tutorial.html
