{-
    BNF Converter: Template Generator
    Copyright (C) 2021  Author:  Grzegorz Dziadkiewicz

-}

-- based on BNFC OCaml backend


module BNFC.Backend.FSharp.CFtoFSharpTemplate (
                    cf2Template
                    ) where

import BNFC.CF
import BNFC.Utils((+++))
import Data.Char
import BNFC.Backend.FSharp.FSharpUtil


type ModuleName = String
type Constructor = String

cf2Template :: ModuleName -> ModuleName  -> CF -> String
cf2Template skelName absName cf = unlines
  [
  "// FSharp module generated by the BNF converter",
  "module "++ skelName,
  "",
  "open " ++ absName,
  "",
  "type Result = string",
  "",
  "let failure x = failwith" +++ "\"Undefined case.\"",
  "",
  unlines $ mutualDefs $ map (\(s,xs) -> case_fun s (toArgs xs)) $ specialData cf ++ cf2data cf
  ]

--TODO: Rewrite in a more readeable way
toArgs [] = []
toArgs ((cons,args):xs)
           = (fixType (TokenCat cons) ++ " " ++ mkTuple (names (map (sanitizeFSharp . var) args) (0 :: Int))) : toArgs xs

--TODO: It is probably bugy for input like ["a", "a", "b", "b"]
names :: [String] -> Int -> [String]
names [] _ = []
names (x:xs) n
    | x `elem` xs = (x ++ show n) : names xs (n+1)
    | otherwise = x : names xs n

var:: Cat -> String
var (ListCat c)      = var c ++ "s"
var (Cat "Ident")    = "id"
var (Cat "Integer")  = "n"
var (Cat "String")   = "str"
var (Cat "Char")     = "c"
var (Cat "Double")   = "d"
var cat              = map toLower (show cat)

case_fun :: Cat -> [Constructor] -> String
case_fun cat xs = unlines $
         [
          "trans" ++ show cat +++ "(x : " ++ fixType cat ++ ") : Result =",
           indent 1 "match x with"
         ] ++
         (map (indent 1) . insertBar . map (++ " -> failure x")) xs

